### ISSUE TITLE
dotnetcore

### ISSUE THREAD

**Issue by XmlmXmlmX** [Retyped/Retyped#11]
dotnetcore support would be nice. Any plans on this?

**Comment by AndreyChechel** [comment]
Hi @XmlmXmlmX,

Thanks for your interest in Bridge.NET and Retyped. 

Retyped project has a focus on JavaScript libraries and the ways of getting their API available for Bridge.NET projects. I'm going to close that issue, since it's irrelevant to Retyped.

So please ask your question in the [Bridge.NET project](https://github.com/bridgedotnet/Bridge), or even better in the [forums](https://forums.bridge.net/).
