### ISSUE TITLE
How to use Function.prototype.call?

### ISSUE THREAD

**Issue by hardhub** [Retyped/Retyped#59]
I cannot find the way to call Array.prototype.slice.call(value) using Retyped.es5.

**Comment by AndreyChechel** [comment]
I'd expect it working using the following C# code:

```cs
var arr = new int[] {1, 2, 3, 4, 5};
Function sliceFn = new Func<double, double, object[]>(Retyped.es5.Array<int>.prototype.slice);
Console.WriteLine(sliceFn.call(arr, 0, 3));
```

However, it doesn't return the expected value. I suspect the reason is `cacheBind` call emitted by Bridge. We'll investigate.

**Comment by AndreyChechel** [comment]
The initial suggestion regarding `cacheBind` is correct. It binds an instance method to the object owner. Unfortunately, JavaScript function can't be "rebound" once bound - that is why the sample above was not working as expected. 

The issue can be fixed by updating the `[Template]` attributes applied to `Function` type methods. The update package is going to be available this week.

**Comment by AndreyChechel** [comment]
Hi @hardhub,

The `[Template]` attributes for methods `apply`, `bind` and `call` of type `Function` were corrected in the following package version. The sample above should be working now. 
- [Retyped.es5 v2.8.6712](https://www.nuget.org/packages/Retyped.es5/2.8.6712)

Also let me suggest another way of "binding" a method to another context. It could be done using Reflection:
```cs
var arr = new int[] {1, 2, 3, 4, 5};

var mi = typeof(Array<int>)
            .GetMethods()
            .Last(x => x.Name == "slice" && 
                       x.ParameterTypes.Length == 2);

var boundDel = (Func<int, int, int[]>) mi.CreateDelegate(typeof(Func<int, int, int[]>), arr);
Console.WriteLine(boundDel(0, 3));
```

In order to make it working you'll need to instruct Bridge to generate metadata at least for `Retyped.es5.Array` type, e.g. in **bridge.json**:
```js
"reflection": {
    "disabled": false,
    "filter":  "Retyped.es5.Array" 
},
```

Reflection-based approach could be not working for some Retyped types including `Retyped.es5.Array` until the issue bridgedotnet/Bridge#3587 is fixed. However, as a temp solution you can manually edit the generated metadata and remove all occurrences of `"td":,` string. Hope that helps.
