### ISSUE TITLE
"DataCloneError: The object could not be cloned." in Firefox

### ISSUE THREAD

**Issue by gitgiggity** [Retyped/Retyped#74]
Found In                   |   Value
---------------------- | --------------------------------------------
Bridge version          |   {17.6.0} 
Package                    |   {Retyped.chrome.chrome2.runtime.sendMessage}  
Package version       |   {0.1.6556}
Declaration file        |    {don't know}

## Description

I think Bridge/Retyped is simply marvellous.

Having programmed in assembly, pascal, and c languages, those were a breeze when compared to the disorganised and objectively ugly JavaScript (I just cant see what all the hype is about).

I am very thankful for how Bridge/Retyped has helped to quickly transform my JavaScript nightmare to the more familiar and sensible C# language.

I don’t know if the following is a bug, but I thought that since no one has brought it up, I’d mention it for the sake of feedback.

## C# sample

```cs
using browser = Retyped.chrome.chrome2;
using JSON = es5.JSON;

var msg = new[] {"Riveting Message"};
browser.runtime.sendMessage(msg);

> Sending this object causes a "DataCloneError: The object could not be cloned." in Firefox
```

## JS Actual

```js
var msg = System.Array.init(["Riveting Message"], System.String);
chrome.runtime.sendMessage(msg);
```

## CS Expected

```cs
var msg = new[] {"Riveting Message"};
browser.runtime.sendMessage(JSON.parse(JSON.stringify(msg)));

> The work-around of converting to Json string, and then back to an object, seems to alleviate it, but that looks rather messy.
```

**Comment by AndreyChechel** [comment]
Hi @gitgiggity,

Thanks for the feedback and kind words about Bridge/Retyped.

According to the information provided [here](https://stackoverflow.com/questions/27558398/datacloneerror-the-object-could-not-be-cloned-in-firefox-34) - the error might relate to the [Structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#Things_that_don't_work_with_structured_clone) that has some requirements to cloning objects. In this case, I don't think there is something needs to be fixed in Bridge/Retyped. What just need to provide a plain object to the Browser API explicitly. It can be done in several ways, e.g. like you suggested, serialize and deserialize an object. Another way is to use `Bridge.toPlain` function:

```cs
var msg = new[] {"Riveting Message"};
var msgPlain = ToPlain(msg);
browser.runtime.sendMessage(msgPlain);

// ...

[Template("Bridge.toPlain({0})")]
public static extern T ToPlain<T>(T obj);
```

Or, you can create a plain object right away without conversion needed -  the **Array** type defined in **Retyped.es5** package can be used for that:

```cs
var msg= new Retyped.es5.Array<string>(new [] {"Riveting Message"});
browser.runtime.sendMessage(msg);
```

**Comment by gitgiggity** [comment]
Thanks, AndreyChechel.
Very helpful.
